import type { Project, SoilLayer, TieRod, LoadCaseDef, ConstructionStage } from "./types";

function today(): string {
  return new Date().toISOString().slice(0, 10);
}

function layer(p: Partial<SoilLayer> & Pick<SoilLayer, "id" | "name" | "zTop" | "zBot">): SoilLayer {
  return {
    description: p.description ?? p.name,
    gamma: 18,
    gammaSat: 20,
    phi: 30,
    c: 0,
    cu: 0,
    E: 20000,
    nu: 0.3,
    kPerm: 1e-5,
    OCR: 1,
    sptN: 10,
    drainage: "drained",
    soilType: "alluvium",
    ...p,
  };
}

function tie(p: Partial<TieRod> & Pick<TieRod, "id" | "name" | "elevation">): TieRod {
  return {
    diameter: 40,
    spacing: 1.5,
    fy: 500,
    fu: 560,
    corrosion: 1,
    threadEff: 0.9,
    connectionEff: 0.9,
    inclination: 0,
    enabled: true,
    ...p,
  };
}

export const defaultLoadCases: LoadCaseDef[] = [
  { id: "LC-01", name: "Dry season / no water", situation: "permanent", waterMode: "dry", trafficOn: false, constructionOn: false, accidentalTieFail: false, oneSidedExcavation: false, enabled: true },
  { id: "LC-02", name: "Rain season / upstream flood", situation: "flood", waterMode: "flood-up", trafficOn: false, constructionOn: false, accidentalTieFail: false, oneSidedExcavation: false, enabled: true },
  { id: "LC-03", name: "Rain season / downstream flood", situation: "flood", waterMode: "flood-down", trafficOn: false, constructionOn: false, accidentalTieFail: false, oneSidedExcavation: false, enabled: true },
  { id: "LC-04", name: "Maximum differential water", situation: "flood", waterMode: "max-diff", trafficOn: false, constructionOn: false, accidentalTieFail: false, oneSidedExcavation: false, enabled: true },
  { id: "LC-05", name: "Heavy traffic + flood", situation: "flood", waterMode: "flood", trafficOn: true, constructionOn: false, accidentalTieFail: false, oneSidedExcavation: false, enabled: true },
  { id: "LC-06", name: "Heavy traffic + dry season", situation: "permanent", waterMode: "dry", trafficOn: true, constructionOn: false, accidentalTieFail: false, oneSidedExcavation: false, enabled: true },
  { id: "LC-07", name: "Construction stage", situation: "construction", waterMode: "dry", trafficOn: false, constructionOn: true, accidentalTieFail: false, oneSidedExcavation: false, enabled: true },
  { id: "LC-08", name: "One-sided excavation / temporary", situation: "temporary", waterMode: "dry", trafficOn: false, constructionOn: false, accidentalTieFail: false, oneSidedExcavation: true, enabled: true },
  { id: "LC-09", name: "Rapid drawdown", situation: "extreme", waterMode: "rapid-drawdown", trafficOn: false, constructionOn: false, accidentalTieFail: false, oneSidedExcavation: false, enabled: true },
  { id: "LC-10", name: "Tie-rod failure / accidental", situation: "accidental", waterMode: "flood", trafficOn: true, constructionOn: false, accidentalTieFail: true, oneSidedExcavation: false, enabled: true },
];

export const defaultStages: ConstructionStage[] = [
  { id: "ST-01", name: "Existing ground", description: "Baseline undeveloped riverbed. Informational only.", tiesInstalled: 0, fillPlaced: false, cappingPlaced: false, roadPlaced: false, trafficOn: false, waterMode: "dry", enabled: true },
  { id: "ST-02", name: "Sheet pile installation", description: "Driving / press-in and lifting of precast units. Handling governs.", tiesInstalled: 0, fillPlaced: false, cappingPlaced: false, roadPlaced: false, trafficOn: false, waterMode: "dry", enabled: true },
  { id: "ST-03", name: "Excavation / river preparation", description: "Temporary unsupported or partially supported excavation.", tiesInstalled: 0, fillPlaced: false, cappingPlaced: false, roadPlaced: false, trafficOn: false, waterMode: "dry", enabled: true },
  { id: "ST-04", name: "Granular fill placement", description: "Core fill placed in layers up to the first tie. Outward pressure before the second tie is locked off.", tiesInstalled: 1, fillPlaced: true, cappingPlaced: false, roadPlaced: false, trafficOn: false, waterMode: "dry", enabled: true },
  { id: "ST-05", name: "Tie installation", description: "First and second tie levels installed and locked off.", tiesInstalled: 2, fillPlaced: true, cappingPlaced: false, roadPlaced: false, trafficOn: false, waterMode: "dry", enabled: true },
  { id: "ST-06", name: "Capping beam", description: "Cast-in-place capping beam tying the wall heads.", tiesInstalled: 2, fillPlaced: true, cappingPlaced: true, roadPlaced: false, trafficOn: false, waterMode: "dry", enabled: true },
  { id: "ST-07", name: "Road construction", description: "Pavement self-weight applied; no live traffic yet.", tiesInstalled: 2, fillPlaced: true, cappingPlaced: true, roadPlaced: true, trafficOn: false, waterMode: "dry", enabled: true },
  { id: "ST-08", name: "Construction traffic", description: "Heavy plant on the platform during construction.", tiesInstalled: 2, fillPlaced: true, cappingPlaced: true, roadPlaced: true, trafficOn: true, waterMode: "dry", enabled: true },
  { id: "ST-09", name: "Flood season", description: "Permanent geometry with wet-season water levels.", tiesInstalled: 2, fillPlaced: true, cappingPlaced: true, roadPlaced: true, trafficOn: false, waterMode: "flood", enabled: true },
  { id: "ST-10", name: "Permanent operation", description: "In-service condition with traffic and dry or wet season as selected.", tiesInstalled: 2, fillPlaced: true, cappingPlaced: true, roadPlaced: true, trafficOn: true, waterMode: "flood", enabled: true },
];

export function defaultProject(): Project {
  return {
    meta: {
      projectName: "Precast RC U-Shape Sheet Pile Flood Protection & Construction Access Road",
      structure: "Double precast RC sheet pile U-embankment with granular core, dual tie rods and RC capping beams",
      option: "Option 3 — Direct Precast RC Sheet Pile & Capping Beam Embankment Dam",
      revision: "A",
      preparedBy: "",
      checkedBy: "",
      date: today(),
      status: "PRELIMINARY DESIGN",
      notes: "Default geometry taken from the Option 3 dry-season and rain-season concept cross-sections.",
    },
    designType: "u-shape-flood",
    wallSystem: "sheet-pile",
    codes: {
      nationalAnnex: "None provided — recommended Eurocode values used provisionally",
      edition: "EN 1990:2002+A1, EN 1991-1-1:2002, EN 1991-2:2003, EN 1992-1-1:2004, EN 1997-1:2004 (first generation)",
      designApproach: "DA2",
      designLife: 50,
      consequenceClass: "CC2",
      reliabilityClass: "RC2",
      executionClass: "EXC2",
      seismic: false,
      includeEn1998: false,
    },
    geometry: {
      retainedHeight: 6,
      embedment: 6,
      roadWidth: 8,
      totalWidth: 8.7,
      wallThickness: 0.35,
      riverbed: 0,
      wallSpacing: 8,
      autoEmbedment: false,
      dMin: 3,
      dMax: 10,
      dStep: 0.25,
    },
    capping: {
      enabled: true,
      b: 0.6,
      h: 0.6,
      cover: 40,
      fck: 32,
      asTop: 1508,
      asBot: 1508,
    },
    pavement: {
      asphalt: 0.2,
      gammaAsphalt: 23,
      subbase: 0.3,
      gammaSubbase: 21,
    },
    sheetPile: {
      fcu: 40,
      fck: 32,
      fyk: 500,
      cover: 40,
      deltaCdev: 10,
      asMainEachFace: 2094,
      asDist: 565,
      barDia: 20,
      barSpacing: 150,
      Ioverride: null,
      Aoverride: null,
      sectionName: "350 mm T&G precast RC sheet pile",
      EcmOverride: null,
      IeffFactor: 0.5,
      nh: 8000,
      khUser: null,
    },
    cbp: {
      diameter: 0.8,
      spacing: 0.95,
      pileLength: 12,
      fck: 35,
      fyk: 500,
      cover: 75,
      barDiameter: 25,
      barCount: 12,
      stirrupDiameter: 12,
      clearGap: 0.15,
      waterCutoff: "none",
      lateralModel: "individual-pile",
      nh: 8000,
      khUser: null,
    },
    coreFill: {
      name: "Compacted granular fill (97% MDD)",
      gamma: 19,
      gammaSat: 21,
      phi: 34,
      c: 0,
      compaction: 97,
      permeability: 1e-4,
      drained: true,
    },
    nativeLayers: [
      layer({
        id: "nat-1",
        name: "Native alluvial soil",
        description: "Upper alluvium at and below riverbed",
        zTop: 0,
        zBot: -3,
        gamma: 18,
        gammaSat: 20,
        phi: 30,
        c: 0,
        E: 15000,
        sptN: 8,
        soilType: "alluvial sand/silt",
      }),
      layer({
        id: "nat-2",
        name: "Medium dense alluvium",
        description: "Lower native founding stratum",
        zTop: -3,
        zBot: -16,
        gamma: 19,
        gammaSat: 21,
        phi: 32,
        c: 0,
        E: 30000,
        sptN: 18,
        soilType: "medium dense sand",
      }),
    ],
    water: {
      gammaW: 9.81,
      dryUp: 0,
      dryDown: 0,
      floodUp: 5.2,
      floodDown: 4.2,
      coreDry: 0,
      coreFlood: 0,
      gwlNative: 0,
    },
    traffic: {
      model: "uniform",
      q: 20,
      axleLoad: 130,
      nAxles: 3,
      axleSpacing: 1.5,
      wheelSpacing: 2.0,
      footprintB: 0.4,
      footprintL: 0.4,
      DAF: 1.3,
      distWidth: 3,
      offsetFromWall: 0.5,
      plantLoad: 15,
      craneLoad: 0,
      stockpile: 0,
    },
    ties: [
      tie({ id: "tie-u", name: "Upper tie rod", elevation: 5.1 }),
      tie({ id: "tie-l", name: "Lower tie rod", elevation: 3.2 }),
    ],
    earth: {
      method: "rankine",
      userKa: 0.3,
      userKp: 3.0,
      wallFriction: 0,
      backfillSlope: 0,
      passiveReduction: 1,
      assumeHorizontal: true,
      assumeDrained: true,
      assumeNoCohesion: true,
      assumeHydrostatic: true,
      assumeNoScour: true,
      assumePassiveMobilised: true,
      useK0IfRestrained: false,
    },
    factors: {
      source: "recommended",
      gammaG: 1.35,
      gammaQ: 1.5,
      gammaGinf: 1.0,
      gammaPhi: 1.25,
      gammaC: 1.25,
      gammaCu: 1.4,
      gammaGamma: 1.0,
      gammaW: 1.35,
      gammaCconc: 1.5,
      gammaS: 1.15,
      alphaCc: 1.0,
      psi0: 0.7,
      psi1: 0.5,
      psi2: 0.3,
    },
    limits: {
      etaPass: 1.0,
      etaWarn: 0.9,
      deflAbs: 50,
      deflSpanRatio: 300,
      wkLimit: 0.2,
      iAllow: 0.5,
      exposure: "XC4 / XF3 (flood structure — confirm)",
      crackForWaterRetaining: true,
    },
    structuralModel: "winkler",
    loadCases: defaultLoadCases,
    stages: defaultStages,
    assumptions: {
      horizontalBackfill: true,
      drainedGranularFill: true,
      noCohesion: true,
      hydrostaticWater: true,
      noSeismic: true,
      uniformTraffic: true,
      passiveMobilised: true,
      noScour: true,
      coreNotRigidDiaphragm: true,
      recommendedNA: true,
    },
  };
}

export const SECTION_LIBRARY = [
  { name: "300 × 150 mm", t: 0.3, b: 0.15 },
  { name: "350 × 200 mm", t: 0.35, b: 0.2 },
  { name: "350 × 250 mm", t: 0.35, b: 0.25 },
  { name: "350 × 300 mm", t: 0.35, b: 0.3 },
  { name: "350 mm T&G (project default)", t: 0.35, b: 1.0 },
  { name: "400 mm T&G", t: 0.4, b: 1.0 },
  { name: "Custom", t: 0.35, b: 1.0 },
];

export const TIE_DIAMETERS = [20, 25, 32, 36, 40, 45, 50];

export const DESIGN_TYPE_LABEL: Record<string, string> = {
  "single-cantilever": "Single cantilever sheet pile",
  "single-anchored": "Single anchored sheet pile",
  "double-sheet": "Double sheet pile",
  "u-shape-core": "U-shape sheet pile + granular core",
  "u-shape-ties": "U-shape sheet pile + tie rods",
  "u-shape-flood": "U-shape flood embankment (ties + capping + core)",
  custom: "Custom configuration",
};
